
package climateControl.customGenLayer;
import climateControl.genLayerPack.GenLayerPack;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

/**
 * @author Zeno410
 */
public abstract class EncodedAddLand extends GenLayerPack {
    private static final String __OBFID = "CL_00000551";

    public EncodedAddLand(long par1, GenLayer par3GenLayer) {
        super(par1);
        this.parent = par3GenLayer;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int par1, int par2, int par3, int par4)
    {
        int i1 = par1 - 1;
        int j1 = par2 - 1;
        int k1 = par3 + 2;
        int l1 = par4 + 2;
        int[] aint = this.parent.getInts(i1, j1, k1, l1);
        int[] aint1 = IntCache.getIntCache(par3 * par4);

        for (int i2 = 0; i2 < par4; ++i2)
        {
            for (int j2 = 0; j2 < par3; ++j2)
            {
                int k2 = aint[j2 + 0 + (i2 + 0) * k1];
                int l2 = aint[j2 + 2 + (i2 + 0) * k1];
                int i3 = aint[j2 + 0 + (i2 + 2) * k1];
                int j3 = aint[j2 + 2 + (i2 + 2) * k1];
                int k3 = aint[j2 + 1 + (i2 + 1) * k1];
                this.initChunkSeed((long)(j2 + par1), (long)(i2 + par2));

                if (decoded(k3) == 0 && (decoded(k2) != 0 || decoded(l2) != 0 || decoded(i3) != 0 || decoded(j3) != 0))
                {
                    int l3 = 1;
                    int i4 = 1;

                    if (decoded(k2) != 0 && this.nextInt(l3++) == 0)
                    {
                        i4 = k2;
                    }

                    if (decoded(l2) != 0 && this.nextInt(l3++) == 0)
                    {
                        i4 = l2;
                    }

                    if (decoded(i3) != 0 && this.nextInt(l3++) == 0)
                    {
                        i4 = i3;
                    }

                    if (decoded(j3) != 0 && this.nextInt(l3++) == 0)
                    {
                        i4 = j3;
                    }

                    if (this.nextInt(3) == 0)
                    {
                        aint1[j2 + i2 * par3] = i4;
                    }
                    else {
                        aint1[j2 + i2 * par3] = k3;
                    }
                }
                else if (decoded(k3) > 0 && (decoded(k2) == 0 || decoded(l2) == 0 || decoded(i3) == 0 || decoded(j3) == 0))
                {
                    if (this.nextInt(5) == 0)
                    {

                        int l3 = 1;
                        int i4 = k3;

                        if (decoded(k2) != 0 && this.nextInt(l3++) == 0)
                        {
                            i4 = k2;
                        }

                        if (decoded(l2) != 0 && this.nextInt(l3++) == 0)
                        {
                            i4 = l2;
                        }

                        if (decoded(i3) != 0 && this.nextInt(l3++) == 0)
                        {
                            i4 = i3;
                        }

                        if (decoded(j3) != 0 && this.nextInt(l3++) == 0)
                        {
                            i4 = j3;
                        }
                        aint1[j2 + i2 * par3] = i4;
                    }
                    else
                    {
                        aint1[j2 + i2 * par3] = k3;
                    }
                }
                else
                {
                    aint1[j2 + i2 * par3] = k3;
                }
            }
        }

        return aint1;
    }

    abstract int decoded(int code);
}