
package climateControl.customGenLayer;

import climateControl.genLayerPack.GenLayerPack;
import com.Zeno410Utils.Zeno410Logger;
import java.util.logging.Logger;
import net.minecraft.init.Biomes;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
/**
 *
 * @author Zeno410
 */
public class GenLayerNoPlains extends GenLayerPack {
    private static int mushroomIsland;
    Logger logger = new Zeno410Logger("NoPlains").logger();

    public GenLayerNoPlains(long par1, GenLayer par3GenLayer){
        super(par1);
        super.parent = par3GenLayer;
        if (super.parent == null) throw new RuntimeException();
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int par1, int par2, int par3, int par4){
        int i1 = par1 ;
        int j1 = par2 ;
        int parentSpan = par3;
        int l1 = par4;
        int[] aint = this.parent.getInts(i1, j1, parentSpan, l1);

        // not sure what's x and z but I need readable variable names
        for (int z = 0; z < par4; z++)
        {
            for (int x = 0; x < par3; x++)
            {
                int center = aint[x  + (z) * parentSpan];

                //logger.info("at "+(x  + (z) * parentSpan)+", "+center);
                if (center == Biome.getIdForBiome(Biomes.PLAINS)) throw new RuntimeException("at "+(x  + (z) * parentSpan));

            }
        }

        return aint;
    }
}
