package climateControl.genLayerPack;
import climateControl.customGenLayer.GenLayerConfirm;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.gen.layer.GenLayer;
public class GenLayerRareBiome extends GenLayerPack
{
    private static final String __OBFID = "CL_00000562";

    public GenLayerRareBiome(long p_i45478_1_, GenLayer p_i45478_3_)
    {
        super(p_i45478_1_);
        this.parent = p_i45478_3_;//new GenLayerConfirm(p_i45478_3_);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int par1, int par2, int par3, int par4)
    {
        int[] aint = this.parent.getInts(par1, par2, par3, par4);

        for (int i1 = 0; i1 < par4; ++i1)
        {
            for (int j1 = 0; j1 < par3; ++j1)
            {
                this.initChunkSeed((long)(j1 + par1), (long)(i1 + par2));
                int k1 = aint[j1  + (i1 ) * (par3)];

                if (this.nextInt(57) == 0)
                {
                    if (k1 == BiomeGenBase.plains.biomeID)
                    {
                        aint[j1 + i1 * par3] = BiomeGenBase.plains.biomeID + 128;
                    }
                }
            }
        }

        return aint;
    }
}